### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(QuickTimerContent)
add_subdirectory(QuickTimer)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	QuickTimerContentplugin
	QuickTimerplugin)